name: ci

on:
  workflow_dispatch:       # tmp: run manually from the actions tab

jobs:    

  # converter job
  convert-files:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      # - run: xml2gmd xml-input gmd-output comments
      # - uses: stefanzweifel/git-auto-commit-action@v4
      # with:
      #    commit_message: generated output from xml2gmd
      #    commit_user_name: converter[job]
      #    commit_user_email: converter[job]@cascade.de
      #    commit_author: converter[job]
      #    commit_options: '--signoff'

  # website job
  build-website:
    runs-on: ubuntu-latest
    needs: convert-files
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      - uses: actions/jekyll-build-pages@v1
        with:
          source: output
          destination: ./_site
      - uses: actions/upload-pages-artifact@v1

  # deployment job
  deploy-website:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-website
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
