name: ci

on:
  workflow_dispatch:       
  push:
    branches: [ "main" ]   
    paths: [ "input/**" ]  
  pull_request:
    branches: [ "main" ]
    paths: [ "input/**" ]
  
env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert polarion files
        run: | 
          gh release download wip --pattern 'gpc' 
          chmod +x gpc
          ./gpc ./input/filelist.txt ./output
          rm gpc 
      - name: Deploy conversion output
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ssh.strato.de >> ~/.ssh/known_hosts
          sshpass -p ${{secrets.SFTP_PASSWORD}} sftp ${{secrets.SFTP_USERNAME}}@ssh.strato.de << !
          PUT -R ./output/*
          BYE
          !
