name: ci

on:
  workflow_dispatch:       
  push:
    branches: [ "main" ]   
    paths: [ "input/**" ]  
  pull_request:
    branches: [ "main" ]
    paths: [ "input/**" ]
  
env:
  GH_TOKEN: ${{ github.token }}

jobs:    

  convert-and-upload:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      
      - uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.GEMSPEC_ONLINE_SFTP_SERVER }}
          port: ${{ secrets.GEMSPEC_ONLINE_SFTP_PORT }}
          user: ${{ secrets.GEMSPEC_ONLINE_SFTP_USERNAME }}
          pass: ${{ secrets.GEMSPEC_ONLINE_SFTP_PASSWORD }}
          run: sftp


    
      #- name: Convert polarion files
      #  run: gh release download wip --pattern 'gpc' 
      #- run: chmod +x gpc
      #- run: ./gpc ./input/filelist.txt ./output
      #- run: rm gpc 
      #- name: Deploy to gemspec.online
      #  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      #  with:
      #      server: ${{ secrets.GEMSPEC_ONLINE_SFTP_SERVER }}
      #      port: ${{ secrets.GEMSPEC_ONLINE_SFTP_PORT }}
      #      username: ${{ secrets.GEMSPEC_ONLINE_SFTP_USERNAME }}
      #      password: ${{ secrets.GEMSPEC_ONLINE_SFTP_PASSWORD }}
      #      local_path: './output/*'
      #      remote_path: '/output/'
      #      sftp_only: true
      #      # delete_remote_files: true




    
  
  
  
  
                     
